services:
  db:
    image: postgres:14
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: matrix
    ports:
      - 5432:5432